### ISSUE TITLE
Training OOM of llama2-7b base on A100 (40GB)

### ISSUE THREAD

**Issue by JintuZheng** [ROIM1998/APT#1]
Hi author, thanks for your nice job! I try to use the default config of "scripts/adaptpruning/llama_2_7b_alpaca_gpt4.sh" to run on a GPU A100 (40GB) but code will OOM. Paper mentioned on Sec."5.4. Main Results", "APT costs less than 24GB of memory when pruning 30% parameters in LLaMA2-7B models before tuning,...", from what I understand this means that the training code can be run on devices with less than 24GB, why i still got the OOM when training on a more than 24GB device.

Is that any settings to change for a limit training without OOM?

P.S.
I have tried to modify the "pruning_batch_size" as 1, and "training_batch_size" as 1, but it didn't work.

**Comment by ROIM1998** [comment]
Hi Jintu. Thanks for raising the issue. Could you please share the error output so I might know which line of code raises the OOM error? Thanks!

**Comment by JintuZheng** [comment]
> Hi Jintu. Thanks for raising the issue. Could you please share the error output so I might know which line of code raises the OOM error? Thanks!

OOM happened in the `loralib/layers.py", line 187, in forward`

Here are the last traceback errors when i used the default script "scripts/adaptpruning/llama_2_7b_alpaca_gpt4.sh":
```
2024-06-27 02:28:38,990 [MainThread  ] [INFO ]  Param per block: {'head_mask': 2097536, 'intermediate_mask': 12289, 'hidden_mask': 1581248}
INFO:prune.pruner:Param per block: {'head_mask': 2097536, 'intermediate_mask': 12289, 'hidden_mask': 1581248}
2024-06-27 02:28:38,991 [MainThread  ] [INFO ]  Using cuda_amp half precision backend
INFO:trainer.trainer_minus:Using cuda_amp half precision backend
2024-06-27 02:28:38,992 [MainThread  ] [INFO ]  Half precision backend: cuda_amp
INFO:trainer.trainer_minus:Half precision backend: cuda_amp
2024-06-27 02:28:38,992 [MainThread  ] [INFO ]  Half precision dtype: torch.bfloat16
INFO:trainer.trainer_minus:Half precision dtype: torch.bfloat16
Evaluating pre-trained model...
2024-06-27 02:28:38,992 [MainThread  ] [INFO ]  ***** Running Evaluation *****
INFO:trainer.trainer_minus:***** Running Evaluation *****
INFO:trainer.trainer_minus:  Num examples = 521
INFO:trainer.trainer_minus:  Batch size = None
2024-06-27 02:28:38,992 [MainThread  ] [INFO ]    Num examples = 521
2024-06-27 02:28:38,993 [MainThread  ] [INFO ]    Batch size = None
Traceback (most recent call last):
  File "run_llama_sft.py", line 146, in <module>
    main()
  File "run_llama_sft.py", line 109, in main
    print(trainer.evaluate())
  File "/root/jt/projects/apt_llama/trainer/trainer_minus.py", line 1844, in evaluate
    output = eval_loop(
  File "/root/jt/projects/apt_llama/trainer/trainer_minus.py", line 1961, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer_seq2seq.py", line 250, in prediction_step
    return super().prediction_step(
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 3376, in prediction_step
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
  File "/root/jt/projects/apt_llama/trainer/trainer_minus.py", line 503, in compute_loss
    outputs = model(**inputs, return_dict=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/jt/projects/apt_llama/models/modeling_llama.py", line 406, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/jt/projects/apt_llama/models/modeling_llama.py", line 586, in forward
    layer_outputs = decoder_layer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/jt/projects/apt_llama/models/modeling_llama.py", line 675, in forward
    hidden_states = self.mlp(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/jt/projects/apt_llama/models/modeling_llama.py", line 918, in forward
    down_proj = self.down_proj(upped_x, use_teacher=use_teacher, in_retained_indices=self.block_retained_indices, out_retained_indices=self.hidden_retained_indices)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/jt/projects/apt_llama/loralib/layers.py", line 187, in forward
    result = F.linear(x, selected_weight, bias=selected_bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 39.39 GiB total capacity; 38.25 GiB already allocated; 30.88 MiB free; 38.86 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by ROIM1998** [comment]
It looks like the OOM occurs when the trainer is evaluating the model (actually this can be just commented out since it's not super useful) before pruning happens. I guess you might be using a relatively large eval batch size with the trainer which results in the OOM. Could you please try reducing the eval batch size or just simply removing all `trainer.valuate()` executions and try again?

**Comment by JintuZheng** [comment]
> It looks like the OOM occurs when the trainer is evaluating the model (actually this can be just commented out since it's not super useful) before pruning happens. I guess you might be using a relatively large eval batch size with the trainer which results in the OOM. Could you please try reducing the eval batch size or just simply removing all `trainer.valuate()` executions and try again?

Thanks for your advice, it is very effective and my training is running well now.
